version = 1

# The bulk of this repository is written work and accompanying diagrams.
[[annotations]]
path = [
  "figures/*.asy",
  "figures/*.tex",
  "notebook.tex",
  "text/*.tex",
]
SPDX-FileCopyrightText = "Ianis Vasilev <ianis@ivasilev.net>"
SPDX-License-Identifier = "CC0-1.0"

# The accompanying code is licensed differently, as well as the files that would be put under the "code" blanket in a software project.
[[annotations]]
path = [
  "**/.gitattributes",
  "**/README.md",
  ".github/**.yml",
  ".gitignore",
  ".python-version",
  "asymptote/**.asy",
  "bibliography/*.bib",
  "classes/*.cls",
  "classes/*.dbx",
  "config.asy",
  "includeonly.sample",
  "Makefile",
  "notebook.asy",
  "packages/*.sty",
  "poe_tasks.toml",
  "pyproject.toml",
  "REUSE.toml",
  "src/**.py",
]
SPDX-FileCopyrightText = "Ianis Vasilev <ianis@ivasilev.net>"
SPDX-License-Identifier = "Unlicense"

# The REUSE documentation suggests licensing generated files under CC0-1.0 with NONE as author.
# https://reuse.software/faq/#exclude-file
[[annotations]]
path = [
  "uv.lock",
  "**/fixtures/*.html",
  "**/fixtures/*.json",
  "**/fixtures/*.xml",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# We use CC0-1.0 for public domain works, as suggested in the REUSE documentation (see above).
[[annotations]]
path = [
  "images/ex__konigsberg_bridges__illustration.png",
]
SPDX-FileCopyrightText = "Copyright © 1652 Matthäus Merian and Martin Zeiller"
SPDX-License-Identifier = "CC0-1.0"

# We use CC0-1.0 for public domain works, as suggested in the REUSE documentation (see above).
[[annotations]]
path = [
  "images/ex__konigsberg_bridges__schematic__drawing.png",
]
SPDX-FileCopyrightText = "Copyright © 1741 Leonhard Euler"
SPDX-License-Identifier = "CC0-1.0"
