[tool.poe.tasks]
test = "pytest"
coverage-collect = "coverage run -m pytest"
coverage-report = "coverage html"
coverage.sequence = ["coverage-collect", "coverage-report"]

[tool.poe.tasks.lint]
sequence = [
  { cmd = "ruff check $path" },
  { cmd = "mypy $path" }
]
args = [
  { name = "path", positional = true, default = "" }
]

[tool.poe.tasks.watcher]
cmd = "python -m commands.watcher"

[tool.poe.tasks.format-matrices]
cmd = "python -m commands.format_matrices"

[tool.poe.tasks.format-bibliography]
cmd = "python -m commands.format_bibliography"

[tool.poe.tasks.find-obsolete-figures]
cmd = "python -m commands.find_obsolete_figures"

[tool.poe.tasks.checkcites]
shell = "cd ..; checkcites --backend biber --all aux/notebook.bcf"
