# poetry
[tool.poetry]
name = "notebook"
version = "1.0.0"
description = "Python code corresponding to my math notebook"
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.12"
rich = "<=13.4.1"
structlog = "^24.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
pytest = "^8.1.1"
pytest-xdist = "^3.5.0"
ruff = "^0.3.5"
coverage = "^7.4.4"

[tool.poetry.group.commands.dependencies]
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^4.0.6"
bibtexparser = "^1.4.1"
titlecase = "^2.4.1"
click = "^8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# poe
[tool.poe]
include = "./poe.toml"

# pytest
[tool.pytest.ini_options]
addopts = "--capture tee-sys --numprocesses auto"
testpaths = "notebook"
python_classes = "!Test"

# ruff
[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D",
  "E501", "E741",
  "G004",
  "S324",
  "ANN101", "ANN102",
  "COM812",
  "FA100", "FA102",
  "TID252",
  "DTZ005",
  "EM",
  "Q",
  "TRY003",
  "S101",
  "PLR1714", "PLR2004",
  "PD",
  "NPY",
  "ERA001",
  "RUF001", "RUF018"
]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 15

# mypy
[tool.mypy]
packages = ["notebook", "commands"]

[[tool.mypy.overrides]]
module = [
  "bibtexparser.*",
  "texoutparse.*",
  "titlecase.*"
]
ignore_missing_imports = true
