[tool.poetry]
name = "notebook.build"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.6.0"
texoutparse = "^1.0.0"
asyncinotify = "^2.0.2"
parsimonious = "^0.9.0"

[tool.poetry.dev-dependencies]
mypy = "^0.971"
pytest = "^7.1.2"
pycodestyle = "^2.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
