# poetry
[tool.poetry]
name = "notebook"
version = "1.0.0"
description = "Python code corresponding to my math notebook"
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.12"
rich = "<=13.4.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
pytest = "^8.1.1"
ruff = "^0.3.4"
coverage = "^7.4.4"

[tool.poetry.group.commands.dependencies]
loguru = "^0.7.2"
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^4.0.6"
bibtexparser = "^1.4.1"
titlecase = "^2.4.1"
click = "^8.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# poe
[tool.poe]
include = "./poe.toml"

# pytest
[tool.pytest.ini_options]
addopts = "--capture tee-sys"
testpaths = "notebook"
python_classes = "!Test"

# ruff
[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
ignore = ["E501", "E741"]
select = ["F401", "I001", "C901", "PLC0105"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 15

# mypy
[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "bibtexparser.*",
  "click.*",
  "texoutparse.*",
  "titlecase.*"
]
ignore_missing_imports = true
