[tool.poetry]
name = "notebook.code"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.12"
loguru = "^0.6.0"
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^4.0.1"
rich = "^13.3.2"

[tool.poetry.group.dev.dependencies]
mypy = "^1.1.1"
pytest = "^7.2.2"
ruff = "^0.0.265"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["E501", "E741"]

[tool.mypy]
check_untyped_defs = true
