[tool.poetry]
name = "notebook.code"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^2.0.5"
rich = "^12.6.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
pytest = "^7.1.3"
pycodestyle = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
check_untyped_defs = true
