[tool.poetry]
name = "notebook.code"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.12"
loguru = "^0.7.2"
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^4.0.6"
rich = "^13.7.0"
bibtexparser = "^1.4.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
pytest = "^7.4.4"
ruff = "^0.1.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--capture tee-sys"
testpaths = "src"

[tool.ruff]
ignore = ["E501", "E741"]

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "bibtexparser.*",
  "texoutparse.*",
  "transliterate.*"
]
ignore_missing_imports = true
