[tool.poetry]
name = "notebook.code"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
texoutparse = "^1.0.0"
asyncinotify = "^2.0.5"
rich = "^12.6.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.990"
pytest = "^7.1.3"
pycodestyle = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = true

[tool.pydocstyle]
# https://flake8.readthedocs.io/en/2.0/warnings.html
# https://github.com/JBKahn/flake8-print/blob/master/flake8_print.py
ignore = ["E241", "E501", "W504"]
