[tool.poetry]
name = "notebook"
version = "1.0.0"
description = ""
authors = ["Ianis Vasilev <ianis@ivasilev.net>"]
license = "Unlicense"
packages = [{ include = "notebook" }]

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"

[tool.poetry.group.commands.dependencies]
loguru = "^0.7.2"
texoutparse = {git = "https://github.com/v--/texoutparse.git"}
asyncinotify = "^4.0.6"
bibtexparser = "^1.4.1"
titlecase = "^2.4.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
pytest = "^8.1.1"
ruff = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--capture tee-sys"
testpaths = "src"
python_classes = "!Test"

[tool.ruff.lint]
ignore = ["E501", "E741"]
select = ["I001", "C901", "PLC0105"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 15

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "bibtexparser.*",
  "texoutparse.*",
  "titlecase.*"
]
ignore_missing_imports = true
