line-length = 120
target-version = "py313"

[format]
quote-style = "single"

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"

[lint]
select = ["ALL"]
ignore = [
  "B027",
  "C408",
  "COM812",
  "D",
  "DTZ001", "DTZ005", "DTZ007",
  "E501", "E741",
  "EM",
  "ERA001",
  "FA100", "FA102",
  "FURB129",
  "G004",
  "NPY",
  "PD",
  "PLC2401",
  "PLR0913", "PLR1714", "PLR2004",
  "PLW3301",
  "PT012",
  "PTH123",
  "PYI041",
  "RET504",
  "RUF001", "RUF003", "RUF018",
  "S101", "S105", "S311", "S314", "S324", "S310", "S603",
  "SIM118", "SIM910",
  "TC002", "TC003",
  "TID252",
  "TRY003",
  "UP031",
]

[lint.isort]
lines-after-imports = 2
known-first-party = ['notebook']

[lint.mccabe]
max-complexity = 15

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"conftest.py" = ["F401"]
