from .axioms import (
    GROUP_ASSOCIATIVITY,
    GROUP_AXIOMS,
    GROUP_COMMUTATIVITY,
    GROUP_INVERSE_LEFT,
    GROUP_INVERSE_RIGHT,
    GROUP_NEUTRAL_LEFT,
    GROUP_NEUTRAL_RIGHT,
)
from .signature import GROUP_SIGNATURE
