name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on:  ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Output git commit info
      run: |
        sudo locale-gen en_US.UTF-8
        make git-commit-info

    - name: Build
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
          apk add make asymptote
          make output/notebook.pdf

    - name: Deploy
      if: success()
      run: |
        echo '${{ secrets.SFTP_KEY }}' > ssh_id
        chmod 600 ssh_id
        echo 'cd ${{ secrets.SFTP_ROOT }}
              put aux/notebook.log
              put output/notebook.pdf
        ' | sftp -i ssh_id -o StrictHostKeyChecking=no -o Port=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}

    - name: Upload only log
      if: failure()
      run: |
        echo '${{ secrets.SFTP_KEY }}' > ssh_id
        chmod 600 ssh_id
        echo 'cd ${{ secrets.SFTP_ROOT }}
              put aux/notebook.log
        ' | sftp -i ssh_id -o StrictHostKeyChecking=no -o Port=${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}
