name: Test

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    if: false
    runs-on:  ubuntu-slim

    steps:
    - uses: actions/checkout@v6

    - name: Setup uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      run: uv sync --frozen

    - name: Lint
      run: uv run --no-sync ruff check

    - name: Typing
      run: uv run --no-sync mypy

    - name: Test
      run: uv run --no-sync pytest
